In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

# datatypes & atributes

In [4]:
a1 = np.array([1,2,3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]], 
            [
                [10,11,12],
                [13,14,15],
                [16,17,18]
            ]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3[0,0,1]

2

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
onesAr = np.ones((2,3))

In [20]:
onesAr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
range_array = np.arange(0,10,2)

In [22]:
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10, size=(3,5))

In [24]:
random_array

array([[3, 9, 3, 6, 8],
       [5, 6, 9, 4, 9],
       [0, 6, 7, 4, 6]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
np.random.random((5,3))

array([[0.06092772, 0.23638543, 0.00120297],
       [0.18725954, 0.85723741, 0.18125658],
       [0.72819271, 0.04501812, 0.76184923],
       [0.36571171, 0.66585975, 0.36794434],
       [0.79075978, 0.76614751, 0.31399407]])

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)

In [30]:
random_array_3

array([[0.6929811 , 0.95621136, 0.16071412],
       [0.12336477, 0.62142219, 0.9682746 ],
       [0.39748143, 0.77401689, 0.45963766],
       [0.1570013 , 0.779644  , 0.88983849],
       [0.7570763 , 0.07748141, 0.29920315]])

In [49]:
#Pseudo-random numbers
np.random.seed(seed=42)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [50]:
random_array_4.shape

(5, 3)

In [59]:
np.random.seed(100)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749]])

In [62]:
np.random.seed(100)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749]])