In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

# datatypes & atributes

In [4]:
a1 = np.array([1,2,3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]], 
            [
                [10,11,12],
                [13,14,15],
                [16,17,18]
            ]])

In [7]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3[0,0,1]

2

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
onesAr = np.ones((2,3))

In [20]:
onesAr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
range_array = np.arange(0,10,2)

In [22]:
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10, size=(3,5))

In [24]:
random_array

array([[3, 9, 3, 6, 8],
       [5, 6, 9, 4, 9],
       [0, 6, 7, 4, 6]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
np.random.random((5,3))

array([[0.06092772, 0.23638543, 0.00120297],
       [0.18725954, 0.85723741, 0.18125658],
       [0.72819271, 0.04501812, 0.76184923],
       [0.36571171, 0.66585975, 0.36794434],
       [0.79075978, 0.76614751, 0.31399407]])

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)

In [30]:
random_array_3

array([[0.6929811 , 0.95621136, 0.16071412],
       [0.12336477, 0.62142219, 0.9682746 ],
       [0.39748143, 0.77401689, 0.45963766],
       [0.1570013 , 0.779644  , 0.88983849],
       [0.7570763 , 0.07748141, 0.29920315]])

In [67]:
#Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [68]:
random_array_4.shape

(5, 3)

In [69]:
np.random.seed(99999)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.20706637, 0.98816574, 0.82692111],
       [0.08839461, 0.77136198, 0.63283161],
       [0.56891059, 0.2748513 , 0.68123322],
       [0.04152483, 0.2646737 , 0.17877627],
       [0.32007609, 0.56231648, 0.02344535]])

In [70]:
np.random.seed(100)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749]])

# 3 Viewing array and matrices

In [71]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [72]:
a1

array([1, 2, 3])

In [73]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [74]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
a3.shape

(2, 3, 3)

In [76]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a2[1]

array([4. , 5. , 6.5])

In [80]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9],
         [9, 3, 2, 5, 8]],

        [[1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2],
         [8, 3, 5, 0, 9]],

        [[3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6],
         [2, 4, 2, 7, 1]]],


       [[[6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0],
         [5, 9, 6, 6, 5]],

        [[6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6],
         [2, 3, 4, 8, 9]],

        [[8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2],
         [3, 6, 4, 1, 3]]]])

In [83]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [87]:
a4[:, :,:,:2]

array([[[[4, 1],
         [4, 3],
         [7, 7],
         [9, 3]],

        [[1, 0],
         [0, 8],
         [8, 1],
         [8, 3]],

        [[3, 6],
         [6, 3],
         [4, 5],
         [2, 4]]],


       [[[6, 6],
         [3, 5],
         [3, 7],
         [5, 9]],

        [[6, 4],
         [2, 3],
         [5, 9],
         [2, 3]],

        [[8, 5],
         [9, 0],
         [2, 0],
         [3, 6]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [90]:
ones = np.ones(3)

array([1, 2, 3])

In [91]:
a1+ones

array([2., 3., 4.])

In [92]:
a1-ones

array([0., 1., 2.])

In [93]:
a1*ones

array([1., 2., 3.])

In [94]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [95]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [97]:
a1 / ones

array([1., 2., 3.])

In [100]:
#flor division
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [101]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [102]:
np.add(a1, ones)

array([2., 3., 4.])

In [103]:
a1+ones

array([2., 3., 4.])