In [2]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

# datatypes & atributes

In [6]:
a1 = np.array([1,2,3])

In [7]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2.0,3.3],
             [4,5,6.5]])
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]], 
            [
                [10,11,12],
                [13,14,15],
                [16,17,18]
            ]])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
a3[0,0,1]

2

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3.shape

(2, 3, 3)

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [23]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2. Creating Arrays

In [28]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [35]:
onesAr = np.ones((2,3))

In [34]:
onesAr

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1.,

In [36]:
range_array = np.arange(0,10,2)

In [37]:
range_array

array([0, 2, 4, 6, 8])

In [40]:
random_array = np.random.randint(0,10, size=(3,5))

In [41]:
random_array

array([[9, 1, 1, 6, 5],
       [5, 1, 2, 8, 0],
       [8, 0, 7, 6, 5]])

In [42]:
random_array.size

15

In [43]:
random_array.shape

(3, 5)

In [44]:
np.random.random((5,3))

array([[0.15757499, 0.54812317, 0.11362746],
       [0.2918385 , 0.35642545, 0.66583846],
       [0.27929312, 0.03787351, 0.98533734],
       [0.6368703 , 0.99394026, 0.39079901],
       [0.36776077, 0.31541298, 0.80652262]])

In [46]:
random_array_2 = np.random.random((5,3))
random_array_2.shape

(5, 3)

In [47]:
random_array_3 = np.random.rand(5,3)

In [48]:
random_array_3

array([[0.57111678, 0.16468343, 0.13023773],
       [0.91243888, 0.21683766, 0.44506381],
       [0.61076506, 0.35022461, 0.2763921 ],
       [0.22580148, 0.26134314, 0.64658434],
       [0.44995314, 0.97377858, 0.56110956]])