# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ],
        [
            [19,20,21],
            [22,23,24],
            [25,26,27]
        ],
    ]
)
arr3[2,1,0]

22

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.size, arr1.ndim, type(arr1), arr1.dtype

((3,), 3, 1, numpy.ndarray, dtype('int32'))

In [4]:
# Attributes of 2-dimensional array
arr2.ndim, arr2.shape, arr2.dtype, type(arr2), arr2.size

(2, (2, 3), dtype('int32'), numpy.ndarray, 6)

In [5]:
# Attributes of 3-dimensional array

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

In [7]:
# Create an array of shape (10, 2) with only ones

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
arr_zeros = np.zeros(shape=(7,2,3))
arr_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
arr_houndred = np.arange(1,100,3)
arr_houndred

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random = np.random.randint(10, size=(7,2))
arr_random

array([[4, 6],
       [3, 7],
       [1, 6],
       [6, 7],
       [9, 8],
       [3, 7],
       [8, 5]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_rand_floats = np.round(np.random.random((3,5)),2)
arr_rand_floats

array([[0.24, 0.58, 0.16, 0.79, 0.55],
       [0.95, 0.18, 0.75, 0.71, 0.37],
       [0.5 , 0.91, 0.77, 0.38, 0.04]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_rand = np.random.randint(10, size=(4,6))
arr_rand

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

# BECAUSE IT IS ALL MAGIC

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(3)
arr_rand = np.random.randint(10, size=(3,7))
# Find the unique numbers in the array you just created
np.unique(arr_rand)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr_rand

array([[8, 9, 3, 8, 8, 0, 5],
       [3, 9, 9, 5, 7, 6, 0],
       [4, 7, 8, 1, 6, 2, 2]])

In [15]:
# Find the 0'th index of the latest array you created
arr_rand[0]

array([8, 9, 3, 8, 8, 0, 5])

In [16]:
# Get the first 2 rows of latest array you created
arr_rand[:2]

array([[8, 9, 3, 8, 8, 0, 5],
       [3, 9, 9, 5, 7, 6, 0]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
arr_rand[:2,:2]

array([[8, 9],
       [3, 9]])

In [18]:
# Get the first 2 values of the first 2 rows of the latest array
arr_rand[:2, :2]

array([[8, 9],
       [3, 9]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand = np.random.randint(10, size=(3,5))
arr_ones = np.ones(shape=(3,5))

In [61]:
# Add the two arrays together
answer = arr_rand + arr_ones
answer

array([[9., 3., 8., 3., 2.],
       [4., 3., 5., 2., 3.],
       [3., 8., 4., 5., 2.]])

In [62]:
# Create another array of ones of shape (5, 3)
arr_once = np.ones(shape=(5,3))

In [75]:
# Try add the array of ones and the other most recent array together
arr_once.shape, answer.shape
arr_once+arr_ones2.T

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [72]:
# Create another array of ones of shape (3, 5)
arr_ones2 = np.ones(shape=(3,5))

In [79]:
# Subtract the new array of ones from the other most recent array
answer = answer-arr_ones2
answer

array([[7., 1., 6., 1., 0.],
       [2., 1., 3., 0., 1.],
       [1., 6., 2., 3., 0.]])

In [82]:
# Multiply the ones array with the latest array
answer=arr_once*answer.T

In [91]:
# Take the latest array to the power of 2 using '**'
answer = np.int_(answer**2)
answer

array([[         0,          0,          1],
       [         1,          1,          0],
       [         0, -501334399,          0],
       [         1,          0, -501334399],
       [         0,          1,          0]])

In [85]:
# Do the same thing with np.square()
np.square(answer)

array([[5.764801e+06, 2.560000e+02, 1.000000e+00],
       [1.000000e+00, 1.000000e+00, 1.679616e+06],
       [1.679616e+06, 6.561000e+03, 2.560000e+02],
       [1.000000e+00, 0.000000e+00, 6.561000e+03],
       [0.000000e+00, 1.000000e+00, 0.000000e+00]])

In [123]:
# Find the mean of the latest array using np.mean()
np.random.seed(42)
test_arr = np.random.randint(101,size=(2,4))
test_arr

array([[51, 92, 14, 71],
       [60, 20, 82, 86]])

In [124]:
np.mean(test_arr)

59.5

In [125]:
# Find the maximum of the latest array using np.max()
np.max(test_arr)

92

In [126]:
# Find the minimum of the latest array using np.min()
np.min(test_arr)

14

In [127]:
# Find the standard deviation of the latest array
np.std(test_arr)

27.613402542968153

In [128]:
# Find the variance of the latest array
np.var(test_arr)

762.5

In [149]:
# Reshape the latest array to (3, 5, 1)
test_arr.reshape(1,1,2,4)


array([[[[51, 92, 14, 71],
         [60, 20, 82, 86]]]])

In [150]:
# Transpose the latest array
test_arr.T

array([[51, 60],
       [92, 20],
       [14, 82],
       [71, 86]])

What does the transpose do?

In [151]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first_arr = np.random.randint(10, size=(3,3))
second_arr = np.random.randint(10, size=(3,2))

In [36]:
# Perform a dot product on the two newest arrays you created


In [37]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [38]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [40]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [41]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [42]:
# Compare the two arrays with '>='


In [43]:
# Find which elements of the first array are greater than 7


In [44]:
# Which parts of each array are equal? (try using '==')


In [45]:
# Sort one of the arrays you just created in ascending order


In [46]:
# Sort the indexes of one of the arrays you just created


In [47]:
# Find the index with the maximum value in one of the arrays you've created


In [48]:
# Find the index with the minimum value in one of the arrays you've created


In [49]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [50]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [51]:
# Create an array of normally distributed random numbers


In [52]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.